### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by Rahul3105** [anwarjitme/green-room-4314#51]

**Comment by Rahul3105** [comment]
Button text is not vertically align
![Screenshot 2023-01-21 at 3 41 52 AM](https://user-images.githubusercontent.com/79327383/213814662-499d503f-9f74-4e24-840e-e2a5b7b6fc62.png)

**Comment by Rahul3105** [comment]
Didn't remove react default icon and title
![Screenshot 2023-01-21 at 3 42 19 AM](https://user-images.githubusercontent.com/79327383/213814810-a938fc23-17ce-489f-bbd0-c519f98848b6.png)

**Comment by Rahul3105** [comment]
"The CRM Platform Your Whole Business Will Love" section in home page, it's button and text is not in center
![Screenshot 2023-01-21 at 3 42 41 AM](https://user-images.githubusercontent.com/79327383/213814957-228c50b4-dbf2-48a7-b392-a3d83e7313e6.png)

**Comment by Rahul3105** [comment]
Signup feature isn't working
![Screenshot 2023-01-21 at 3 48 31 AM](https://user-images.githubusercontent.com/79327383/213815290-c8f0b378-ee36-449b-82cf-d1e36b9df19c.png)

**Comment by anwarjitme** [comment]
Can I work on it after construct week project??
